[package]
name = "a2"
version = "0.1.0"
authors = ["Brian Myers <brian.carl.myers@gmail.com>"]

categories = ["Algorithms", "API bindings", "Authentication", "Cryptography"]
description = "Idiomatic Argon2 password hashing"
documentation = "httpss://docs.rs/a2"
homepage = "https://github.com/bcmyers/a2"
keywords = ["argon2", "argon2i", "argon2id", "argon2d", "crypto", "hash", "password"]
license = "MIT"
publish = false
readme = "README.md"
repository = "https://github.com/bcmyers/a2"

build = "build.rs"
links = "argon2"

[dependencies]
base64 = "0.9"
bitflags = "1.0"
failure = "0.1"
rand = "0.4"
serde = { version = "1.0", optional = true }
void = "1.0"

[build-dependencies]
bindgen = "0.35"
cc = "1.0"

[dev-dependencies]
bindgen = "0.35"
dotenv = "0.11"

[badges]
travis-ci = { repository = "bcmyers/a2", branch = "master" }
