[package]
name = "a2"
version = "0.1.0"
authors = ["Brian Myers <brian.carl.myers@gmail.com>"]

categories = ["Algorithms", "API bindings", "Authentication", "Cryptography"]
description = "Idiomatic Argon2 password hashing"
documentation = "httpss://docs.rs/a2"
homepage = "https://github.com/bcmyers/a2"
keywords = ["argon2", "argon2i", "argon2id", "argon2d", "crypto", "hash", "password"]
license = "MIT"
publish = false
readme = "README.md"
repository = "https://github.com/bcmyers/a2"

build = "build.rs"
links = "argon2"

[dependencies]
base64 = "0.9"
bindgen = "0.35"
bitflags = "1.0"
# blake2-rfc = "0.2"
failure = "0.1"
lazy_static = "1.0"
log = "0.4"
nom = "4.0"
num_cpus = "1.8"
rand = "0.4"
scopeguard = "0.3"
serde = "1.0"
serde_derive = "1.0"

[build-dependencies]
bindgen = "0.35"
cc = { version = "1.0", features = ["parallel"] }

[dev-dependencies]
dotenv = "0.11"
env_logger = "0.5"
serde_json = "1.0"

[badges]
travis-ci = { repository = "bcmyers/a2", branch = "master" }
