version: '3'
services:
  tests:
    command: bash -c 'cargo test --release --features="native simd serde" -- --nocapture'
    build: .
    environment:
      - LD_LIBRARY_PATH=/usr/lib:/usr/local/lib:/usr/lib/x86_64-linux-gnu/
      - RUST_BACKTRACE=1
    volumes:
      - .:/home/dev/argonautica
      - target:/home/dev/argonautica/target
    working_dir: /home/dev/argonautica

volumes:
  target:
