version: '3'
services:
  tests:
    command: bash -c "cargo test --features serde"
    build: .
    environment:
      - LD_LIBRARY_PATH=/usr/lib:/usr/local/lib
      - RUST_BACKTRACE=1
    volumes:
      - .:/home/dev/a2
      - target:/home/dev/a2/target
    working_dir: /home/dev/a2

volumes:
  target:
