version: '3'
services:
  tests:
    command: bash -c "cargo test --release test_c_version -- --nocapture"
    build: .
    environment:
      - LD_LIBRARY_PATH=/usr/lib:/usr/local/lib:/usr/lib/x86_64-linux-gnu/
      - RUST_BACKTRACE=1
    volumes:
      - .:/home/dev/a2
      - target:/home/dev/a2/target
    working_dir: /home/dev/a2

volumes:
  target:
