unstable_features = true

force_multiline_blocks = true
match_block_trailing_comma = true
reorder_extern_crates = true
reorder_extern_crates_in_group = true
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
reorder_modules = true
use_field_init_shorthand = true
use_try_shorthand = true
